version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "aws-samples/hostfactory-maintainers"
    assignees:
      - "aws-samples/hostfactory-maintainers"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  # Docker dependencies (merged configuration)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "aws-samples/hostfactory-maintainers"
    assignees:
      - "aws-samples/hostfactory-maintainers"
    groups:
      docker:
        patterns:
          - "*"
