# Bandit configuration file
# https://bandit.readthedocs.io/en/latest/config.html

# Skip specific tests globally
skips: []

# File patterns to exclude
exclude_dirs:
  - '.git'
  - '.venv'
  - 'tests'
  - 'docs'
  - 'examples'
  - 'build'
  - 'dist'
  - '*.egg-info'

# Tests to run
tests:
  - B101  # assert_used
  - B102  # exec_used
  - B103  # set_bad_file_permissions
  - B104  # hardcoded_bind_all_interfaces
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B107  # hardcoded_password_default
  - B108  # hardcoded_tmp_directory
  - B110  # try_except_pass
  - B112  # try_except_continue
  - B201  # flask_debug_true
  - B301  # pickle
  - B302  # marshal
  - B303  # md5
  - B304  # ciphers
  - B305  # cipher_modes
  - B306  # mktemp_q
  - B307  # eval
  - B308  # mark_safe
  - B309  # httpsconnection
  - B310  # urllib_urlopen
  - B311  # random
  - B312  # telnetlib
  - B313  # xml_bad_cElementTree
  - B314  # xml_bad_ElementTree
  - B315  # xml_bad_expatreader
  - B316  # xml_bad_expatbuilder
  - B317  # xml_bad_sax
  - B318  # xml_bad_minidom
  - B319  # xml_bad_pulldom
  - B320  # xml_bad_etree
  - B321  # ftplib
  - B323  # unverified_context
  - B324  # hashlib_new_insecure_functions
  - B325  # tempnam
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_sax
  - B407  # import_xml_expat
  - B408  # import_xml_minidom
  - B409  # import_xml_pulldom
  - B410  # import_lxml
  - B411  # import_xmlrpclib
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B603  # subprocess_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_rawsql_used
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B703  # django_mark_safe

# Severity levels
any_other_function_with_shell_equals_true: HIGH
assert_used: LOW
hardcoded_bind_all_interfaces: MEDIUM
hardcoded_password_default: LOW
hardcoded_password_funcarg: LOW
hardcoded_password_string: LOW
hardcoded_sql_expressions: MEDIUM
hardcoded_tmp_directory: LOW
linux_commands_wildcard_injection: HIGH
paramiko_calls: HIGH
password_config_option_not_marked_secret: LOW
request_with_no_cert_validation: HIGH
set_bad_file_permissions: MEDIUM
ssl_with_bad_defaults: MEDIUM
ssl_with_bad_version: HIGH
start_process_with_a_shell: HIGH
start_process_with_no_shell: HIGH
start_process_with_partial_path: HIGH
subprocess_popen_with_shell_equals_true: HIGH
subprocess_without_shell_equals_true: HIGH
try_except_continue: LOW
try_except_pass: LOW
use_of_mako_templates: HIGH
weak_cryptographic_key: HIGH

# Output format
output_format: text

# Confidence levels
confidence_levels:
  LOW: 0.0
  MEDIUM: 0.5
  HIGH: 0.95

# Number of lines of context to display for each issue
context_lines: 3

# Show code snippets in output
show_code: true

# Show line numbers in output
show_lineno: true

# Show progress bar
progress: true

# Aggregate output by filename
aggregate_by_filename: true

# Exit with 0 status if no security issues are found
exit_zero: false
