name: Container Build and Publish

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile*'
      - 'src/**'
      - 'pyproject.toml'
      - 'deployment/docker/**'
      - 'dev-tools/scripts/container-build.sh'
      - '.github/workflows/container.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile*'
      - 'src/**'
      - 'pyproject.toml'
      - 'deployment/docker/**'
      - 'dev-tools/scripts/container-build.sh'
      - '.github/workflows/container.yml'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  get-python-versions:
    name: Get Python Versions from Makefile
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.versions.outputs.python-versions }}
      default-python: ${{ steps.versions.outputs.default-python }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract Python versions from Makefile
      id: versions
      run: |
        # Extract PYTHON_VERSIONS from Makefile
        PYTHON_VERSIONS=$(grep "^PYTHON_VERSIONS :=" Makefile | cut -d'=' -f2 | xargs)
        DEFAULT_PYTHON=$(grep "^DEFAULT_PYTHON :=" Makefile | cut -d'=' -f2 | xargs)
        
        # Convert to JSON array for matrix
        PYTHON_VERSIONS_JSON=$(echo "$PYTHON_VERSIONS" | tr ' ' '\n' | jq -R . | jq -s .)
        
        echo "python-versions=$PYTHON_VERSIONS_JSON" >> $GITHUB_OUTPUT
        echo "default-python=$DEFAULT_PYTHON" >> $GITHUB_OUTPUT
        
        echo "Found Python versions: $PYTHON_VERSIONS"
        echo "Default Python version: $DEFAULT_PYTHON"

  container-build:
    name: Build Container Images
    runs-on: ubuntu-latest
    needs: get-python-versions
    
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.get-python-versions.outputs.python-versions) }}
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    
    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get package metadata from Makefile
      id: package
      run: |
        # Source environment and get package info
        source .venv/bin/activate 2>/dev/null || python -m venv .venv && source .venv/bin/activate
        pip install -e . >/dev/null 2>&1 || true
        
        # Get values from Makefile (fallback to defaults if not available)
        CONTAINER_REGISTRY=$(make -s --no-print-directory -f Makefile print-CONTAINER_REGISTRY 2>/dev/null || echo "ghcr.io/awslabs")
        CONTAINER_IMAGE=$(make -s --no-print-directory -f Makefile print-CONTAINER_IMAGE 2>/dev/null || echo "open-hostfactory-plugin")
        VERSION=$(make -s --no-print-directory -f Makefile print-VERSION 2>/dev/null || echo "latest")
        
        echo "registry=$CONTAINER_REGISTRY" >> $GITHUB_OUTPUT
        echo "image=$CONTAINER_IMAGE" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Build container using dev-tools script
      env:
        REGISTRY: ${{ steps.package.outputs.registry }}
        IMAGE_NAME: ${{ steps.package.outputs.image }}
        VERSION: ${{ steps.package.outputs.version }}
        PYTHON_VERSION: ${{ matrix.python-version }}
        PLATFORMS: linux/amd64,linux/arm64
        PUSH: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.event_name == 'release' || github.event.inputs.push_images == 'true') }}
        CACHE: true
      run: |
        chmod +x dev-tools/scripts/container-build.sh
        ./dev-tools/scripts/container-build.sh
    
    - name: Test container image
      if: matrix.python-version == needs.get-python-versions.outputs.default-python
      run: |
        # Test that the container starts and responds to health check
        IMAGE_TAG="${{ steps.package.outputs.registry }}/${{ steps.package.outputs.image }}:${{ steps.package.outputs.version }}-python${{ matrix.python-version }}"
        
        echo "Testing container image: $IMAGE_TAG"
        
        # Run container in background
        docker run --rm -d --name test-container \
          -p 8000:8000 \
          "$IMAGE_TAG"
        
        # Wait for container to start
        echo "Waiting for container to start..."
        sleep 15
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f http://localhost:8000/health || exit 1
        
        echo "Container test passed!"
        
        # Stop test container
        docker stop test-container

  container-manifest:
    name: Create Multi-Architecture Manifests
    runs-on: ubuntu-latest
    needs: [get-python-versions, container-build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.event_name == 'release')
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get package metadata
      id: package
      run: |
        # Get values using same method as build job
        source .venv/bin/activate 2>/dev/null || python -m venv .venv && source .venv/bin/activate
        pip install -e . >/dev/null 2>&1 || true
        
        CONTAINER_REGISTRY=$(make -s --no-print-directory -f Makefile print-CONTAINER_REGISTRY 2>/dev/null || echo "ghcr.io/awslabs")
        CONTAINER_IMAGE=$(make -s --no-print-directory -f Makefile print-CONTAINER_IMAGE 2>/dev/null || echo "open-hostfactory-plugin")
        VERSION=$(make -s --no-print-directory -f Makefile print-VERSION 2>/dev/null || echo "latest")
        
        echo "registry=$CONTAINER_REGISTRY" >> $GITHUB_OUTPUT
        echo "image=$CONTAINER_IMAGE" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create and push manifests
      env:
        PYTHON_VERSIONS: ${{ join(fromJSON(needs.get-python-versions.outputs.python-versions), ' ') }}
        DEFAULT_PYTHON: ${{ needs.get-python-versions.outputs.default-python }}
        REGISTRY: ${{ steps.package.outputs.registry }}
        IMAGE: ${{ steps.package.outputs.image }}
        VERSION: ${{ steps.package.outputs.version }}
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          # Create manifest for latest
          MANIFEST_IMAGES=""
          for py_ver in $PYTHON_VERSIONS; do
            MANIFEST_IMAGES="$MANIFEST_IMAGES $REGISTRY/$IMAGE:$VERSION-python$py_ver"
          done
          
          echo "Creating manifest for latest with images: $MANIFEST_IMAGES"
          docker manifest create $REGISTRY/$IMAGE:latest $MANIFEST_IMAGES
          docker manifest push $REGISTRY/$IMAGE:latest
        fi
        
        if [ "${{ github.event_name }}" = "release" ]; then
          # Create manifest for release version
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          MANIFEST_IMAGES=""
          for py_ver in $PYTHON_VERSIONS; do
            MANIFEST_IMAGES="$MANIFEST_IMAGES $REGISTRY/$IMAGE:$RELEASE_VERSION-python$py_ver"
          done
          
          echo "Creating manifest for $RELEASE_VERSION with images: $MANIFEST_IMAGES"
          docker manifest create $REGISTRY/$IMAGE:$RELEASE_VERSION $MANIFEST_IMAGES
          docker manifest push $REGISTRY/$IMAGE:$RELEASE_VERSION
        fi
