name: Container Security Scan

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.dockerignore'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.dockerignore'
  schedule:
    # Run container security scan weekly on Tuesdays at 5 AM UTC
    - cron: '0 5 * * 2'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  container-security:
    name: Container Security Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:security-scan
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:security-scan
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Trivy vulnerability scanner (JSON output)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:security-scan
        format: 'json'
        output: 'trivy-results.json'

    - name: Run Snyk container security scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:security-scan
        args: --severity-threshold=high --file=Dockerfile
      continue-on-error: true

    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: snyk.sarif
      continue-on-error: true

    - name: Docker Scout security scan
      uses: docker/scout-action@v1
      if: always()
      with:
        command: cves
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:security-scan
        sarif-file: scout-results.sarif
        summary: true
      continue-on-error: true

    - name: Upload Docker Scout results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: scout-results.sarif
      continue-on-error: true

    - name: Dockerfile security scan with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        format: sarif
        output-file: hadolint-results.sarif
        no-fail: true

    - name: Upload Hadolint results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: hadolint-results.sarif

    - name: Upload container security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: container-security-reports
        path: |
          trivy-results.sarif
          trivy-results.json
          snyk.sarif
          scout-results.sarif
          hadolint-results.sarif
        retention-days: 30

    - name: Container security summary
      if: always()
      run: |
        echo "## Container Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Scans Performed:" >> $GITHUB_STEP_SUMMARY
        echo "- Trivy vulnerability scan" >> $GITHUB_STEP_SUMMARY
        echo "- Snyk container security scan" >> $GITHUB_STEP_SUMMARY
        echo "- Docker Scout security analysis" >> $GITHUB_STEP_SUMMARY
        echo "- Hadolint Dockerfile security scan" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the Security tab for detailed SARIF results." >> $GITHUB_STEP_SUMMARY
