name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  get-config:
    name: Get Configuration
    runs-on: ubuntu-latest
    outputs:
      default-python-version: ${{ steps.config.outputs.default-python-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Get project configuration
      id: config
      uses: ./.github/actions/get-config

  validate-workflows:
    name: Validate Workflow Files
    runs-on: ubuntu-latest
    needs: get-config

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Python and UV
      uses: ./.github/actions/setup-python-uv
      with:
        python-version: ${{ needs.get-config.outputs.default-python-version }}
        cache-key-suffix: validate-workflows

    - name: Validate workflow syntax and logic
      run: |
        make validate-workflow-syntax

    - name: Validate workflows with actionlint
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        ./actionlint -color
      shell: bash

    - name: Validate shell scripts with shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: '.venv .git __pycache__ node_modules'
