name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate-yaml:
    name: Validate Workflow YAML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code

    - name: Install yq
      uses: mikefarah/yq@master
      uses: actions/checkout@v5

    - name: Validate workflow files
      run: |
        echo "Validating GitHub Actions workflow YAML files..."
        for file in .github/workflows/*.yml .github/workflows/*.yaml; do
          if [ -f "$file" ]; then
            echo "Validating $file..."
            yq . "$file" > /dev/null && echo "VALID: $file" || (echo "INVALID: $file" && exit 1)
          fi
        done
        echo "All workflow files are valid!"
