name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate-yaml:
    name: Validate Workflow YAML
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    
    - name: Validate workflow files
      run: |
        echo "Validating GitHub Actions workflow YAML files..."
        for file in .github/workflows/*.yml .github/workflows/*.yaml; do
          if [ -f "$file" ]; then
            echo "Validating $file..."
            yq . "$file" > /dev/null && echo "✓ $file is valid" || (echo "✗ $file is invalid" && exit 1)
          fi
        done
        echo "All workflow files are valid!"
