name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  get-config:
    name: Get Configuration
    runs-on: ubuntu-latest
    outputs:
      default-python-version: ${{ steps.config.outputs.default-python-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install yq
      uses: mikefarah/yq@master

    - name: Get configuration from project config
      id: config
      run: |
        DEFAULT_PYTHON_VERSION=$(make print-DEFAULT_PYTHON_VERSION)
        echo "default-python-version=$DEFAULT_PYTHON_VERSION" >> "$GITHUB_OUTPUT"

  validate-workflows:
    name: Validate Workflow Files
    runs-on: ubuntu-latest
    needs: get-config

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ needs.get-config.outputs.default-python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Validate workflow syntax and logic
      run: |
        make validate-all-workflows
