name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate-workflows:
    name: Validate Workflow Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install yq
      uses: mikefarah/yq@master

    - name: Validate workflow syntax and logic
      run: |
        make validate-all-workflows
